package org.finalframework.data.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.reflect.Method;

import org.springframework.core.annotation.AliasFor;
import org.springframework.data.annotation.Persistent;

/**
 * Marked the element is a {@literal virtual} property, it's value generated by a {@linkplain Json json}. A
 * {@linkplain Virtual} column is normal annotated on a {@linkplain Method getter} method.
 *
 * <p>
 * <pre>
 *         <code>
 *             ALTER TABLE {tableName} ADD {virtual column name} {virtual column type} GENERATED ALWAYS AS JSON_UNQUOTE({column}->{path});
 *         </code>
 *     </pre>
 * </p>
 *
 * @author likly
 * @version 1.0
 * @date 2020-03-16 22:59
 * @see Column
 * @since 1.0
 */
@Documented
@Persistent
@Column
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Virtual {

    @AliasFor(annotation = Column.class)
    String value() default "";

    @AliasFor(annotation = Column.class)
    String name() default "";
}
