package org.ifinal.finalframework.annotation.data;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.reflect.Method;
import org.springframework.core.annotation.AliasFor;

/**
 * Marked the element is a {@literal virtual} property, it's value generated by a {@linkplain Json json}. A {@linkplain
 * Virtual} column is normal annotated on a {@linkplain Method getter} method.
 *
 * <pre class="code">
 *      ALTER TABLE {tableName} ADD {virtual column name} {virtual column type}
 *      GENERATED ALWAYS AS JSON_UNQUOTE({column}-&gt;{path});
 * </pre>
 *
 * @author likly
 * @version 1.0.0
 * @see Column
 * @see Prefix
 * @since 1.0.0
 */
@Prefix("v_")
@Column
@Documented
@Target({ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Virtual {

    @AliasFor(annotation = Column.class)
    String value() default "";

    @AliasFor(annotation = Column.class)
    String name() default "";

}
